// Generated by gencpp from file dm_arm_msgs_srvs/dm_arm_cmd.msg
// DO NOT EDIT!


#ifndef DM_ARM_MSGS_SRVS_MESSAGE_DM_ARM_CMD_H
#define DM_ARM_MSGS_SRVS_MESSAGE_DM_ARM_CMD_H

#include <ros/service_traits.h>


#include <dm_arm_msgs_srvs/dm_arm_cmdRequest.h>
#include <dm_arm_msgs_srvs/dm_arm_cmdResponse.h>


namespace dm_arm_msgs_srvs
{

struct dm_arm_cmd
{

typedef dm_arm_cmdRequest Request;
typedef dm_arm_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct dm_arm_cmd
} // namespace dm_arm_msgs_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dm_arm_msgs_srvs::dm_arm_cmd > {
  static const char* value()
  {
    return "ab876838156246ec2905cd94b5756b0a";
  }

  static const char* value(const ::dm_arm_msgs_srvs::dm_arm_cmd&) { return value(); }
};

template<>
struct DataType< ::dm_arm_msgs_srvs::dm_arm_cmd > {
  static const char* value()
  {
    return "dm_arm_msgs_srvs/dm_arm_cmd";
  }

  static const char* value(const ::dm_arm_msgs_srvs::dm_arm_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::dm_arm_msgs_srvs::dm_arm_cmdRequest> should match
// service_traits::MD5Sum< ::dm_arm_msgs_srvs::dm_arm_cmd >
template<>
struct MD5Sum< ::dm_arm_msgs_srvs::dm_arm_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dm_arm_msgs_srvs::dm_arm_cmd >::value();
  }
  static const char* value(const ::dm_arm_msgs_srvs::dm_arm_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dm_arm_msgs_srvs::dm_arm_cmdRequest> should match
// service_traits::DataType< ::dm_arm_msgs_srvs::dm_arm_cmd >
template<>
struct DataType< ::dm_arm_msgs_srvs::dm_arm_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::dm_arm_msgs_srvs::dm_arm_cmd >::value();
  }
  static const char* value(const ::dm_arm_msgs_srvs::dm_arm_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dm_arm_msgs_srvs::dm_arm_cmdResponse> should match
// service_traits::MD5Sum< ::dm_arm_msgs_srvs::dm_arm_cmd >
template<>
struct MD5Sum< ::dm_arm_msgs_srvs::dm_arm_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dm_arm_msgs_srvs::dm_arm_cmd >::value();
  }
  static const char* value(const ::dm_arm_msgs_srvs::dm_arm_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dm_arm_msgs_srvs::dm_arm_cmdResponse> should match
// service_traits::DataType< ::dm_arm_msgs_srvs::dm_arm_cmd >
template<>
struct DataType< ::dm_arm_msgs_srvs::dm_arm_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::dm_arm_msgs_srvs::dm_arm_cmd >::value();
  }
  static const char* value(const ::dm_arm_msgs_srvs::dm_arm_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DM_ARM_MSGS_SRVS_MESSAGE_DM_ARM_CMD_H
